apiVersion: v1
entries:
  fpga-xrt-driver:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-14T13:34:51.596107016+05:30"
    description: A Helm chart for Kubernetes
    digest: 91d8fa90cb83731460d2ecb0ea8a0e53606d45d678fc8b5db4d0ae2307b83a99
    name: fpga-xrt-driver
    type: application
    urls:
    - file:///charts/xilinx/fpga-xrt-driver-4.7.11.tgz
    version: 4.7.11
generated: "2021-10-14T13:34:51.595795829+05:30"


