apiVersion: v1
entries:
  driver-container-base:
  - annotations:
      appVersion: '>= 1.13.0 < 1.15.0'
    apiVersion: v2
    appVersion: 1.0.0
    created: "2021-08-19T14:26:57.19324935Z"
    description: Driver Container Base is the base image for out-of-tree builds
    digest: 1c7b14a4e2cd8ad5851064047c03365184a9dd29f5ecbb978ca4c2ac3af82f7b
    icon: https://avatars.githubusercontent.com/u/55542927
    name: driver-container-base
    type: application
    urls:
    - file:///charts/deprecated/driver-container-base-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-19T14:26:57.19284407Z"
